Feat/tela desafio
gamaacademy-labs/challenges-web pull request #4
Opened 2022-08-31 21:36 UTC by ZaidaCueto

2022-09-01 14:09 UTC, israel53 approved these changes

2022-09-08 13:02 UTC, NikolasRoger requested changes

2022-09-08 13:02 UTC, NikolasRoger commented on src/pages/_app.tsx
> +import { Header } from '../components/header'
esse import é necessário? tendo em vista que o componente Header não está sendo utilizado nesse arquivo

2022-09-08 13:02 UTC, NikolasRoger commented on src/pages/iniciar-desafio.tsx
> +const PaginaDesafios = () => {
Utilizar palavra em inglês para definir o nome do componente para seguirmos o padrão

2022-09-08 13:02 UTC, NikolasRoger commented on src/pages/iniciar-desafio.tsx
> +import { Box, MaterialIcon, Tag, Tooltip, Typography } from '@gama-academy/smash-web'
imports desnecessários

2022-09-08 13:02 UTC, NikolasRoger commented on src/pages/pagina-desafios.tsx
> +import { Box, MaterialIcon, Tag, Tooltip, Typography } from '@gama-academy/smash-web'
imports desnecessários

2022-09-08 13:02 UTC, NikolasRoger commented on src/pages/pagina-desafios.tsx
> +const PaginaDesafios = () => {
Padrão de escrita deve ser em inglês

2022-09-08 13:02 UTC, NikolasRoger commented on src/services/challenges.ts
> +    export interface challenges{
tipos devem ficar em um arquivo separado, services/challenges.types.ts

2022-09-08 13:02 UTC, NikolasRoger commented on src/templates/challenges-page/challenges-page.templetes.tsx
> +const ChallengesPageTempletes = () => {
Nome do arquivo e nome do component com escrita incorreta > templetes, deve ser templates

2022-09-08 13:02 UTC, NikolasRoger commented on src/templates/challenges-page/challenges-page.templetes.tsx
> +import { getChallenges } from '../../services/challenges';
não é necessário fazer esse import aqui, já que nao está sendo utilizado

2022-09-08 21:39 UTC, merged