Feat: created orientation modal
gamaacademy-labs/challenges-web pull request #9
Opened 2022-09-09 21:12 UTC by ZaidaCueto

2022-09-10 12:03 UTC, NikolasRoger requested changes

2022-09-10 12:03 UTC, NikolasRoger commented on src/components/modal/modal.comp.tsx
> +const Modal: React.FC<ModalProps> = ({ isShowing, toggle, children }) => {
Ao invés de criarmos um componente de modal, podemos utilizar o componente ja pronto que possui todas as funcionalidades necessárias, que está no SMASH

2022-09-10 12:03 UTC, NikolasRoger commented on src/templates/challenge/components/deliverables-list/deliverables-list.comp.tsx
> +import { Box, Card, MaterialIcon, Modal, Typography } from '@gama-academy/smash-web'
Import desnecessário, já que nao está sendo utilizado em nenhum lugar

2022-09-10 12:03 UTC, NikolasRoger commented on src/templates/start-challenge/components/start-footer/start-footer.comp.tsx
> +            <Modal {...{ isShowing, toggle }}>
Podemos criar o modal como um componente da pagina de start challenge, para deixar o código mais limpo, algo como: orientation-modal

2022-09-12 11:50 UTC, NikolasRoger approved these changes

2022-09-12 16:18 UTC, Leonardo-SARTO-Conselheiro approved these changes

2022-09-12 16:18 UTC, merged